#################################
# Author : H0llyW00dzZ (Hacker) #
#################################
name: Manual Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3
      # use github container which is free unlike dockerhub which is paid
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/h0llyw00dzz/go-urlshortener:latest
   # This ensures the cleanup runs even if the build fails
    - name: Clean up Buildx builder
      if: always()
      run: docker buildx rm
